# Generated by Django 5.2.9 on 2026-01-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news', '0002_predictionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
